export const VALIDATION_FORM = "VALIDATION_FORM";
export const VALIDATION_FORM_SUCCESS = "VALIDATION_FORM_SUCCESS";
export const VALIDATION_FORM_ERROR = "VALIDATION_FORM_ERROR ";

export const ADD_PRODUCT = "ADD_PRODUCT";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_ERROR = "ADD_PRODUCT_ERROR";

export const START_DOWNLOAD_PRODUCTS = "START_DOWNLOAD_PRODUCTS ";
export const DOWNLOAD_PRODUCTS_SUCCESS = "DOWNLOAD_PRODUCTS_SUCCESS";
export const DOWNLOAD_PRODUCTS_ERROR = "DOWNLOAD_PRODUCTS_ERROR ";

export const GET_PRODUCT_DELETE = "GET_PRODUCT_DELETE";
export const PRODUCT_DELETE_SUCCESS = "PRODUCT_DELETE_SUCCESS";
export const PRODUCT_DELETE_ERROR = "PRODUCT_DELETE_ERROR";

export const GET_PRODUCT_EDIT = "GET_PRODUCT_EDIT";
export const PRODUCT_EDIT_SUCCESS = "PRODUCT_EDIT_SUCCESS";
export const PRODUCT_EDIT_ERROR = "PRODUCT_EDIT_ERROR";

export const START_EDITING_PRODUCT = "START_EDITING_PRODUCT";
export const PRODUCT_EDITED_SUCCESS = "PRODUCT_EDITED_SUCCESS";
export const PRODUCT_EDITED_ERROR = "PRODUCT_EDITED_ERROR";
